### PR TITLE
Don't score invalid words

### LINKED ISSUE #272: Scrabbling a word without any letters throws an error
Saying something without any letters in it throws an error in the bot's console (e.g. `####`)

```
Error processing message event:
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Client.message (modules/scrabble.js:118:30)
    at Client.fireEvents (/modules/fireEvents.js:16:28)
```

### LINKED ISSUE #273: Bot will shout about invalid words even when we don't want it to
If you say a high scoring word that doesn't fit on a Scrabble board, the bot will complain at you instead of suffering silently:
```
< human> this has gone catastrophically wrong
<+bot> human: not a valid word
```

### PR DESCRIPTION
**Pull request by georgewatson**
Fixes #273.

~~I'll try to also work on #272 before merging this.~~

Fixes #272

### CODE REVIEW

File: modules/scrabble.js [hunk 1]
```diff
@@ -81,7 +81,7 @@ function scrabbleScore (str) {
     .reduce((a, b) => ({
       'score': a['score'] + b['score'],
       'usedBlanks': a['usedBlanks'] + b['usedBlanks']
-    }))
+    }), { 'score': 0, 'usedBlanks': 0 })
```
Comment (zuzak) [inline modules/scrabble.js]: you don't need quotes here
```suggestion
    }), { score: 0, usedBlanks: 0 })
```

File: modules/scrabble.js [hunk 2]
```diff
@@ -112,10 +112,11 @@ module.exports = {
       let words = []
       phrase.forEach((word) => {
         word = word.replace(/[^A-Z]+$/, '')
-        if (wordHistory.includes(word) || word === '') return
-        words.push(computeWord(word))
+        let result = computeWord(word)
+        if (wordHistory.includes(word) || !result.isPossible) return
```
Comment (zuzak) [inline modules/scrabble.js]: this should probably be `result.word` because line 121 is
(otherwise the various transforms could be inconsistent)

thinking about it, you don't need the `.toUpperCase()` on line 111 anymore?
